### ISSUE TITLE
Generator: Add deprecated support

### ISSUE THREAD

**Issue by TimAufdemKampe** [mittwald/api-client-js#166]
If I mark a field of my api spec as `deprecated: true` my spec get invalid.

```
properties:
    lastMessageAt:
        type: string
        format: date-time
        deprecated: true
```

Docs: https://openapispec.com/docs/how/how-does-openapi-handle-api-deprecation/#deprecation-of-schema-properties
